# Generated by Django 5.2.4 on 2025-08-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('xp', models.PositiveIntegerField()),
                ('icon', models.CharField(max_length=16)),
                ('reward', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quest_number', models.PositiveIntegerField(unique=True)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('xp', models.PositiveIntegerField()),
                ('icon', models.CharField(max_length=16)),
                ('story', models.TextField()),
                ('modules', models.JSONField(default=list)),
                ('boss_battle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['quest_number'],
            },
        ),
    ]
